#!/bin/bash
#PBS -N eval_all_last_test
#PBS -P personal-kenneth0
#PBS -l select=1:ngpus=1:ncpus=8:mem=40gb
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -o /scratch/users/ntu/kenneth0/FYP-SmartObjectCounter/logs/eval_all_last_test.out
#PBS -e /scratch/users/ntu/kenneth0/FYP-SmartObjectCounter/logs/eval_all_last_test.err

REPO=/scratch/users/ntu/kenneth0/FYP-SmartObjectCounter
cd "$REPO" || exit 1

module purge
module load pytorch/2.6.0-py3-cu11.8
export PYTHONPATH="$REPO:$PYTHONPATH"

set -e

python -u scripts/eval_rgbt.py --mode rgb   --split test --data_root ./data/RGBT-CC-CVPR2021 --ckpt outputs/rgb_e100_count_ema/ckpt_last.pt
python -u scripts/eval_rgbt.py --mode t     --split test --data_root ./data/RGBT-CC-CVPR2021 --ckpt outputs/t_e100_count_ema/ckpt_last.pt
python -u scripts/eval_rgbt.py --mode early --split test --data_root ./data/RGBT-CC-CVPR2021 --ckpt outputs/rgbt_early_e100_count_ema/ckpt_last.pt
python -u scripts/eval_rgbt.py --mode late  --split test --data_root ./data/RGBT-CC-CVPR2021 --ckpt outputs/rgbt_late_e100_count_ema/ckpt_last.pt
